# Generated by Django 5.2.11 on 2026-02-09 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_url', models.URLField(max_length=2000)),
                ('api_key', models.CharField(blank=True, default='', max_length=500)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('data_path', models.CharField(blank=True, default='', help_text="JSON path to the array of items, e.g. 'products' or 'data.items'", max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ingesting', 'Ingesting'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('document_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
