# Generated by Django 5.2.11 on 2026-02-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisource',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='source_pdfs/'),
        ),
        migrations.AddField(
            model_name='apisource',
            name='source_type',
            field=models.CharField(choices=[('api', 'API'), ('pdf', 'PDF')], default='api', max_length=10),
        ),
        migrations.AlterField(
            model_name='apisource',
            name='api_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
