# Generated by Django 5.2.11 on 2026-02-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_apisource_pdf_file_apisource_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisource',
            name='agent_role',
            field=models.TextField(blank=True, default='', help_text='Optional custom role/instructions for the AI agent for this source.'),
        ),
    ]
